from __future__ import annotations
from datetime import datetime
from html import escape
from collections import Counter

def render_report(meta, findings, title='Check Point Firewall Configuration Audit'):
    counts=Counter(f.status for f in findings); assessed=[f for f in findings if f.status in ('Compliant','Non-Compliant','Partially Compliant')]
    score=round(100*sum(1 for f in assessed if f.status=='Compliant')/len(assessed),1) if assessed else 0
    def badge(s): return f'<span class="badge {s.lower().replace(" ","-")}">{escape(s)}</span>'
    rows=''.join(f'''<tr><td>{escape(f.id)}</td><td>{escape(f.title)}</td><td>{escape(f.category)}</td><td>{badge(f.status)}</td><td>{escape(f.severity)}</td><td>{f.confidence}%</td></tr>''' for f in findings)
    details=''.join(f'''<section class="finding"><h3>{escape(f.id)} — {escape(f.title)}</h3><div class="grid"><div><b>Status</b><br>{badge(f.status)}</div><div><b>Severity</b><br>{escape(f.severity)}</div><div><b>Confidence</b><br>{f.confidence}%</div><div><b>Category</b><br>{escape(f.category)}</div></div><h4>Finding</h4><p><b>Expected:</b> {escape(f.expected)}</p><p><b>Observed:</b> {escape(f.observed)}</p><h4>Impact</h4><p>{escape(f.impact)}</p><h4>Remediation</h4><p>{escape(f.remediation)}</p><h4>Evidence</h4><pre>{escape(f.evidence)}</pre><p class="source">Source: {escape(f.source)} | Mapping: {escape(f.cis_reference)}</p></section>''' for f in findings)
    return f'''<!doctype html><html><head><meta charset="utf-8"><title>{escape(title)}</title><style>
body{{font:14px Arial,sans-serif;margin:0;background:#f4f7fb;color:#172033}} header{{background:#10243e;color:white;padding:34px 6%}} main{{max-width:1200px;margin:auto;padding:24px}} .cards{{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px;margin:20px 0}} .card,.finding{{background:white;border:1px solid #dfe7f1;border-radius:10px;padding:18px;box-shadow:0 2px 8px #0001}} .num{{font-size:28px;font-weight:bold}} table{{width:100%;border-collapse:collapse;background:white}} th,td{{padding:10px;border-bottom:1px solid #e6edf5;text-align:left}} th{{background:#eaf0f7}} .badge{{padding:4px 8px;border-radius:12px;font-size:12px;font-weight:bold}} .compliant{{background:#d9f7e6;color:#075b32}} .non-compliant{{background:#ffe0e0;color:#8b1111}} .not-assessed,.manual-review-required{{background:#fff0c7;color:#735000}} .grid{{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}} pre{{white-space:pre-wrap;background:#111827;color:#e5e7eb;padding:14px;border-radius:8px;overflow:auto}} .source{{font-size:12px;color:#607086}} @media print{{body{{background:white}} .finding{{break-inside:avoid}}}} </style></head><body><header><h1>{escape(title)}</h1><p>Evidence-driven assessment with confidence scoring and false-positive suppression</p><p>Device: {escape(meta.get('hostname','Unknown'))} | Version: {escape(meta.get('version','Unknown'))} | Generated: {datetime.now().isoformat(timespec='seconds')}</p></header><main><div class="cards"><div class="card"><div class="num">{score}%</div>Assessed compliance</div><div class="card"><div class="num">{counts['Compliant']}</div>Compliant</div><div class="card"><div class="num">{counts['Non-Compliant']}</div>Non-Compliant</div><div class="card"><div class="num">{counts['Manual Review Required']}</div>Manual Review</div><div class="card"><div class="num">{counts['Not Assessed']}</div>Not Assessed</div></div><h2>Assessment Summary</h2><table><thead><tr><th>ID</th><th>Title</th><th>Category</th><th>Status</th><th>Severity</th><th>Confidence</th></tr></thead><tbody>{rows}</tbody></table><h2>Detailed Findings and Evidence</h2>{details}<h2>Assessment Notes</h2><p>Missing evidence is not treated as failure. Historical logs do not override authoritative active configuration. Policy checks require management API or rulebase exports. Secrets and IP addresses are masked in the report.</p><p>Archive SHA-256: {escape(meta.get('sha256',''))}</p></main></body></html>'''
